### ISSUE TITLE
음식 정보 띄워주는 화면 만들기

### ISSUE THREAD

**Issue by SnowSuno** [dayscout-kaist/dayscout-app#4]
# Todo

- [x] 영양정보 표시
- [x] 섭취량 입력 페이지로 이동
- [ ] 영양정보 수정 화면 제작
- [ ] 상세정보 펼치기

**Comment by injoonH** [comment]
<img width="400" alt="FoodInfo" src="https://github.com/dayscout-kaist/dayscout-app/assets/50509417/cc105c04-0b46-47f7-a701-5a32038c0a4f">
